fix: Debounce the scroll event, to make Chrome happy
ietf-tools/datatracker pull request #3958
Opened 2022-05-13 13:17 UTC by larseggert

2022-05-13 19:02 UTC, NGPixel requested changes

2022-05-13 19:02 UTC, NGPixel commented on ietf/static/js/ietf.js
> +                }, 20));
I would suggest using a value like `100` ms debounce if it achieves the same result. I've found using values under 100 ms to be unreliable in many scenarios.

2022-05-13 19:02 UTC, NGPixel commented on package.json
> +    "lodash.debounce": "4.0.8",
As suggested above, replace with the full `lodash` library instead.

2022-05-16 17:27 UTC, NGPixel approved these changes

2022-05-16 20:56 UTC, larseggert commented
The failing check should be fixed by #3975

2022-05-18 19:01 UTC, merged