feat: add pronouns to Person and oidc claims. Fixes #4043.
ietf-tools/datatracker pull request #4059
Opened 2022-06-03 19:57 UTC by rjsparks

2022-06-06 21:21 UTC, jennifer-richards requested changes
This looks like it should work (and seems to, though I have not exercised the OIDC claim directly). A couple comments, though.

This implementation differs from the description in #4043. The specification there seems to ask for checkboxes with the standard options, allowing zero or more to be selected, plus one for the free-form entry. That strikes me as an odd format, but it's described specifically enough that I wonder if there's a particular demand for it?

UI-wise, I have mixed feelings about the hinted text field. The only hint to the user of the format expected comes from the autocomplete options that show up when they start typing. An old fashioned radio or checkbox would make it clearer, which might be especially helpful for people unfamiliar with the practice of specifying one's pronouns.

Also, the display of the pronouns on the profile page seems to emphasize the pronouns disproportionately. I.e., they're on their own line with a font size larger than all but the person's name.

Marking this as "Request changes," but it's really more of a request to consider/confirm the design change compared to the ticket (and probably a little bike shedding).

2022-06-17 19:23 UTC, rjsparks commented
02cbf1a tries a different approach, using a MultiWidget (CheckboxSelectMultiple and TextInput), but the form mechanics are convoluted and it will still need more validation. Will try separate model (not just form) fields next.

2022-06-18 21:20 UTC, rjsparks commented on ietf/ietfauth/forms.py
> +            pronouns = pronouns.strip()
All the above is OBE - this code took a different path

2022-06-21 19:36 UTC, jennifer-richards approved these changes
The changes look good - the modeling is a little awkward, but seems like a good compromise given the constraints of Django's fields/widgets.

My only suggestion is that the display on the profile page still feels a little too "in your face". Playing with it, getting rid of the \<br> and dropping the font to fs-4 or -5 instead of fs-3 gives me something that seems a little more like a typical name badge level of attention to the pronouns.

Could iterate forever on aesthetics and page design, though, so I'm approving.

2022-06-21 20:02 UTC, merged