feat: point to Zulip chat rather than jabber.
ietf-tools/datatracker pull request #4218
Opened 2022-07-14 20:58 UTC by rjsparks

2022-07-14 21:08 UTC, NGPixel requested changes

2022-07-14 22:04 UTC, jennifer-richards requested changes
This seems to be missing a migration to convert `GroupFeatures.has_default_jabber` to `GroupFeatures.has_default_chat` (or am I missing something?).

Grepping the code I find one spot where `jabber` should probably be changed to `chat` (line 732 of `ietf_filters.py`), but it's just a comment. The only other `jabber` I see is either old migrations or relates to a `jabber_room` in group extresources.

A few other questions / comments inline.

2022-07-15 15:43 UTC, rjsparks commented on ietf/group/migrations/0002_groupfeatures_historicalgroupfeatures.py
> +                ('has_default_chat', models.BooleanField(default=False, verbose_name='Chat')),
migration is missing - the GroupFeatures model is changed.

2022-07-15 15:53 UTC, rjsparks commented on ietf/group/migrations/0002_groupfeatures_historicalgroupfeatures.py
> +                ('has_default_chat', models.BooleanField(default=False, verbose_name='Chat')),
And the HistoricalGroupFeatures model was removed at group/0039, but this is a good catch, this migration shouldn't have been touched.

2022-07-15 17:21 UTC, jennifer-richards commented on ietf/templates/group/group_about.html
> +                        <a href="{{ group.chat_archive_url }}">
oob, Robert indicated that it's ok to drop the logs - they're still findable and could be added via extresources if needed.

2022-07-15 17:22 UTC, jennifer-richards approved these changes

2022-07-15 18:46 UTC, NGPixel approved these changes

2022-07-15 18:48 UTC, merged