Fix: Update timezone on the interim create page
ietf-tools/datatracker pull request #4262
Opened 2022-07-24 00:11 UTC by meadmaker

The interim creation screen will set the timezone to the timezone of
the browser.  Unfortunately, the UI element was never refreshed, so
it remained on its loaded default, thus telling the user the wrong
value.

This change adds a timezone widget refresh to the end of the function that
loads the browser's local timezone into the timezone value.

This change also adds code to update the 'Local timezone' help text
for the start time and end time input bozes to
call out the selected timezone specifically.

(Finally, it adds a newline at the end of the file, since none was present previously)

Fixes #3898

2022-07-24 14:16 UTC, jennifer-richards requested changes
Looks good, just some minor lint.

It strikes me as a little awkward that we now have to hook up the change event on the timezone input before we call `initTimeZone()`. It might be worth adding a comment to discourage someone from "helpfully" switching that around.

2022-07-24 14:16 UTC, jennifer-richards commented on ietf/static/js/meeting-interim-request.js
> +            var tzname = $(this).val();
Should use `const tzname` - we're trying to rid the codebase of `var`

2022-07-26 16:42 UTC, NGPixel approved these changes

2022-07-26 17:15 UTC, jennifer-richards approved these changes

2022-07-26 17:16 UTC, merged