fix: work around dataTransfer.getData limitation in agenda editor
ietf-tools/datatracker pull request #4553
Opened 2022-10-07 19:47 UTC by jennifer-richards

The agenda editor was broken as of Chrome 106 without this patch. It's a bit of a hack, but I believe it respects the letter of the relevant specs.

2022-10-07 20:48 UTC, rjsparks requested changes

2022-10-07 20:48 UTC, rjsparks commented on ietf/static/js/edit-meeting-schedule.js
> +            console.log(`Hiya: {sessionElement}`);
Leftover debug?

2022-10-07 22:11 UTC, jennifer-richards commented on ietf/static/js/edit-meeting-schedule.js
> +            console.log(`Hiya: {sessionElement}`);
Ugh, yes. Removed.

2022-10-10 13:48 UTC, rjsparks approved these changes

2022-10-10 13:48 UTC, merged