fix: 4635
ietf-tools/datatracker pull request #4700
Opened 2022-11-05 14:27 UTC by russhousley

Don't send I-D expiration warning if it will happen within 12 hours.

2022-11-05 14:53 UTC, jennifer-richards requested changes
This is targeting main - would be nice to aim it at feat/tzaware instead. For either branch, replacing `datetime.datetime.now()` with `timezone.now()` as noted inline is preferable.

2022-11-05 14:53 UTC, jennifer-richards commented on ietf/doc/expire.py
> +    now_plus_12hours = datetime.datetime.now() + datetime.timedelta(hours=12)
Should be `timezone.now()` instead of `datetime.datetime.now()`

2022-11-06 12:29 UTC, rjsparks commented
I'll retarget this and make the changes to use timezone.

2022-11-08 15:50 UTC, jennifer-richards approved these changes

2022-11-08 16:06 UTC, merged