fix: Allow more email addresses in notification lists
ietf-tools/datatracker pull request #4792
Opened 2022-11-24 12:18 UTC by larseggert

Fixes #4736

2022-11-28 16:57 UTC, rjsparks requested changes
This is insufficient - a matching change to the document model is also needed, or the extra bits won't be stored in the database. See  https://github.com/ietf-tools/datatracker/blob/main/ietf/doc/models.py#L111. 

It's not immediately clear whether leaving this as a `CharField` in the model and making it significantly larger is the right thing to do. I suspect it probably needs to be converted to a `TextField`. Either way, the change will need to be accompanied by a migration effecting the change in the database.

(You build that with something like `ietf/maange.py makemigrations doc` after changing the model.)

2022-12-05 15:41 UTC, rjsparks requested changes

2022-12-05 15:41 UTC, rjsparks commented on ietf/doc/migrations/send_notices.py
> +# Generated by Django 2.2.28 on 2022-12-05 14:37
This needs to be renamed to be 0048_send_notices.py (Though i'd suggest 0048_longer_notify_field.py)

2022-12-05 21:01 UTC, rjsparks approved these changes

2022-12-06 15:45 UTC, jennifer-richards approved these changes
Only comment is that I'd probably have named the migration something more descriptive (`0048_lengthen_notification_lists` or something), but that's a small nit. Looks good otherwise.

2022-12-08 21:46 UTC, merged

2022-12-08 22:11 UTC, uzkjzjjz commented
![Notes_221114_232000_f65](https://user-images.githubusercontent.com/106896911/206578070-47ee7043-dcf2-461e-af10-2ccfa0a5267c.jpg)