fix: Don't expose existing emails via reset password and account creation forms
ietf-tools/datatracker pull request #5288
Opened 2023-03-07 09:50 UTC by larseggert

Replaces #5254. Rebase to feat/postgres.

2023-03-07 16:25 UTC, rjsparks requested changes

2023-03-07 16:25 UTC, rjsparks commented on ietf/ietfauth/views.py
> +                to_email = user.first().person.email_address() if user else new_account_email
This could still leave us sending mail to the address provided in the form. Instead, I think we want the else here to be email.first().person.email_address()?

2023-03-07 16:25 UTC, rjsparks commented
_Thank you_ for the rebase effort

2023-03-07 16:31 UTC, larseggert commented on ietf/ietfauth/views.py
> +                to_email = user.first().person.email_address() if user else new_account_email
Wouldn't that be the same email?

2023-03-07 16:32 UTC, jennifer-richards commented on ietf/ietfauth/views.py
> +                to_email = user.first().person.email_address() if user else new_account_email
Nothing is easy... 

* even if `user is not None`, `user.email_address()` might be `''`
* an `Email` might exist but be disabled

I think we probably want `person_to_contact = user.person if user else email.person.user`. Then we contact `person.email_address()` if that's not empty, and finally throw it at an admin to deal with it because something fishy is going on.

2023-03-07 16:45 UTC, jennifer-richards commented on ietf/ietfauth/views.py
> +                to_email = user.first().person.email_address() if user else new_account_email
> Wouldn't that be the same email?

Maybe not (e.g., https://0xsha.io/blog/the-fall-of-mighty-django-exploiting-unicode-case-transformations#exploiting-unicode-case-transformations).

The main thing here is that we want to alert a validated address that this attempt has been made, which means not trusting the POSTed value.

(Though I suspect a collision like this would mean an active attempt at hijacking. In that case, we're not really preventing an information leak any more, just trying to be sure a Real Person is informed.)

2023-03-09 08:40 UTC, larseggert commented on ietf/ietfauth/views.py
> +                to_email = user.first().person.email_address() if user else new_account_email
Laptop died and am waiting for a replacement. I can pick this up later, or you can make the change if you need to merge before that.

2023-03-14 17:24 UTC, rjsparks approved these changes

2023-03-15 18:40 UTC, jennifer-richards approved these changes
Looks ok - I think it will leak the existence of an email / username in the case that the user has no active email addresses, but I think that's probably not an exploitable situation.

2023-03-15 22:27 UTC, merged