feat: endpoint for imapd to authenticate against
ietf-tools/datatracker pull request #5295
Opened 2023-03-12 19:53 UTC by rjsparks

2023-03-12 19:55 UTC, rjsparks commented
Feel free to suggest a different direction for this.

2023-03-13 17:48 UTC, jennifer-richards requested changes
I think we need to fail if `User.objects.filter(username__iexact=username).count() > 1` (equivalently, if `User.objects.get(username__iexact=username)` raises `user.MultipleObjectsReturned`). Otherwise, if `User` records `A` and `B` are somehow created with a username collision under `iexact`, whichever `User` comes up as `first()` can log in using either username. Assuming imapd is simply passing the username over as it receives it, it would then allow that password holder to access either account.

This is different from the cases we've dealt with before. If we want to treat it the same way, we would need to report back to imapd not only "success" but the actual username we used in deciding it was a success.

2023-03-13 17:57 UTC, jennifer-richards approved these changes

2023-03-14 17:19 UTC, merged

2023-03-18 07:10 UTC, VeselinPersinov reviewed
Hi nice to meet you