Update "You've been nominated" email
ietf-tools/datatracker pull request #5357
Opened 2023-03-16 18:05 UTC by richsalz

Mention that the schedule is posted to ietf-announce and give a link to subscribe to that.  Use vague wording to handle all cases.

2023-03-16 18:12 UTC, richsalz commented
Sorry for the noise; forced push/rebase etc.  Learning how to submit PR's here.

2023-03-16 18:46 UTC, rjsparks requested changes

2023-03-16 18:46 UTC, rjsparks commented on ietf/dbtemplate/fixtures/nomcom_templates.xml
This file is essentially legacy - it was used to populate the database long ago, and is not used by e.g. the tests. 

Changes here will not affect production.
What you really want is a migration that changes a row in the database. I can show you how to build that.

2023-03-16 18:46 UTC, rjsparks commented on ietf/nomcom/migrations/0001_initial.py
This migration has long ago been run. Changing it here has no effect on production. Please revert this file in your branch.

2023-03-16 18:46 UTC, rjsparks commented on ietf/dbtemplate/fixtures/nomcom_templates.xml
After we create the migration you want, (or edit the template in the database directly), you'll need to revert this file in your branch

2023-03-16 18:46 UTC, rjsparks commented on ietf/nomcom/models.py
> +                                             help_text='If you check this box, questionnaires are sent automatically after nominations. DO NOT CHECK if they are not ready yet.')
This is fine, but it also needs a new companion migration.

2023-03-16 18:47 UTC, rjsparks commented on ietf/nomcom/migrations/0001_initial.py
(again, hold until we create the migration you really wanted so we can translate your suggestion into the migration.)

2023-03-25 02:49 UTC, jennifer-richards commented on ietf/nomcom/migrations/0001_initial.py
> +                ('send_questionnaire', models.BooleanField(default=False, help_text='If you check this box, questionnaires are sent automatically after nominations. DO NOT CHECK if they are not ready
Should add a new migration instead of modifying this one

2023-03-25 02:55 UTC, rjsparks approved these changes

2023-03-25 02:55 UTC, rjsparks commented
holding to bring in after the postgres transition is complete

2023-04-13 22:12 UTC, richsalz commented
I think this is ready for review now.

2023-04-23 23:07 UTC, merged