feat: import IAB minutes from the IAB wordpress site
ietf-tools/datatracker pull request #5689
Opened 2023-05-25 16:39 UTC by rjsparks

Work in Progress

2023-05-25 17:50 UTC, jennifer-richards reviewed
One (very minor) nit inline.

I wonder whether the migration is the right way to frame this update? You plan to run a management command to add the files. Would it make more sense to do this whole job with a management command? It's really more of a data injection than a migration, and splitting up the task between a migration and a management command invites things to get out of sync.

Edit to add: may want to add docevents to describe how the new items got into the database?

2023-05-25 17:50 UTC, jennifer-richards commented on ietf/meeting/migrations/0005_iabminutes.py
> +    for year in ntby.keys():
Minor nit: probably better to iterate over a dict with `for year in ntby` without the `.keys()`. (Does the same thing, but does not have to set up a dictionary view.)

2023-06-09 16:03 UTC, jennifer-richards requested changes
Couple minor things

2023-06-09 16:24 UTC, rjsparks commented on ietf/meeting/management/commands/import_iab_minutes.py
> +    with open(PurePath(__file__).parent.joinpath("data_for_import_iab_minutes"),"r") as file:
Just trying to follow the documentation for PurePath vs Path - the literature is a mess around it. I'm happy to change as you suggest.

2023-06-09 17:30 UTC, rjsparks commented on ietf/group/views.py
> +    sessions = group.session_set.with_current_status().filter(
So, I changed it here. It's not clear what the original intent of making acronym optional was, but the implementation clearly requires it.

2023-06-09 17:44 UTC, jennifer-richards approved these changes

2023-06-09 22:07 UTC, merged