feat: require draft revisions in ipr disclosures. Explain missing ones.
ietf-tools/datatracker pull request #6160
Opened 2023-08-16 21:39 UTC by rjsparks

2023-08-17 14:42 UTC, jennifer-richards approved these changes
Approved! (A couple style nits and a possible (but not required) refactor noted inline.)

2023-08-17 14:53 UTC, larseggert commented on ietf/ipr/templatetags/ipr_filters.py
> +    revs_before = NewRevisionDocEvent.objects.filter(doc=draft, time__lte=time).order_by('-time')
draft -> Internet-Draft (per guidance from @ghwood)

2023-08-17 14:54 UTC, larseggert requested changes
draft -> Internet-Draft everywhere

2023-08-17 15:56 UTC, rjsparks commented
This also needs to test another facet - commit incoming

2023-08-18 00:28 UTC, jennifer-richards approved these changes

2023-08-18 12:47 UTC, merged