test: Add tests for case sensitivity
ietf-tools/datatracker pull request #6194
Opened 2023-08-23 19:11 UTC by pselkirk

This also includes changes to existing tests to deal with case-sensitivity issues that were revealed by temporarily hard-wiring PersonFactory to use an upper-case or mixed-case email address.

This testing was done while researching  #5929 and #6057. This testing didn't result in code changes outside of the test code, so it's not imperative that it be merged.

2023-08-25 15:32 UTC, jennifer-richards requested changes
It looks to me like something is missing - see the comment about `do_submission()`.

There's an inline suggestion about keyword-only arguments. That's more a question about whether you think it'd be appropriate than a demand - we haven't used keyword-only args in the code so far, but I think it's something we should consider.

2023-08-25 15:32 UTC, jennifer-richards commented on ietf/submit/tests.py
> +    def submit_existing(self, formats, author=None, email=None, change_authors=True, group_type='wg', stream_type='ietf'):
These new parameters don't seem to be used in the method, or am I missing something?

2023-08-25 15:32 UTC, jennifer-richards commented on ietf/submit/tests.py
> +            submitter=author.formatted_email().upper(),
I'd suggest an assertion that `author.formatted_email().upper() != author.formatted_email()` just to be airtight

2023-09-12 01:54 UTC, jennifer-richards requested changes
I probably should have caught this on the first pass, but I still don't think `email` is making it all the way down into the test.

2023-09-12 01:54 UTC, jennifer-richards commented on ietf/submit/tests.py
> +    def do_submission(self, name, rev, group=None, formats: Tuple[str, ...]=("txt",), author=None, email=None, base_filename=None, ascii=True):
I should probably have caught this the first time around, but I don't think this `email` parameter is used either. Worries me that the test is not testing what it means to test.

2024-02-26 18:52 UTC, rjsparks commented
Closing this as OBE. We can come back to it as part of a future cleanup effort.

2024-02-26 18:52 UTC, closed without merging