feat: Capture that IPR disclosures are removed under the Objectively False IPR Disclosure Policy
ietf-tools/datatracker pull request #6231
Opened 2023-08-28 20:30 UTC by pselkirk

Implements #6088

2023-09-07 15:35 UTC, rjsparks requested changes

2023-09-07 15:35 UTC, rjsparks commented on ietf/settings.py
> +PUBLISH_IPR_STATES = ['posted', 'removed', 'removed_objfalse']
Minor tweak needed: Please move this above the `if not production` block. Just before is fine (unless you see some other puddle of ipr app related settings to attach it to).

2023-09-11 17:41 UTC, jennifer-richards approved these changes

2023-09-11 18:14 UTC, rjsparks approved these changes

2023-09-11 18:14 UTC, merged