fix: Add link to public pages to private NomCom pages
ietf-tools/datatracker pull request #6345
Opened 2023-09-21 14:22 UTC by larseggert

Fixes #6343

Also fix highlighting of the active tab in the nav tab bar while I'm here, and remove old links that 404. Oh, and force-break some long/bogus UTF8 names.

2023-09-22 05:32 UTC, larseggert commented
I opened #6355 for the spurious CI failure.

2023-09-22 14:22 UTC, jennifer-richards requested changes
I'm a little worried about hard-to-maintain template logic, see inline comments. I think probably the best thing would be to replace `if selected in "a,b"` with `if selected == "a" or selected == "b"` and leave the logic that computes the `selected` as it is.

2023-09-22 14:22 UTC, jennifer-richards commented on ietf/templates/nomcom/nomcom_public_base.html
> +    {% with selected=l0|default:l1 %}
Clever but pushing the limits of what's a good idea in template logic. Might be better as a template filter if there's any chance we'd want this logic elsewhere.

2023-09-22 14:22 UTC, jennifer-richards commented on ietf/templates/nomcom/nomcom_public_base.html
> +                <a class="nav-link dropdown-toggle {% if selected in 'eligible,volunteers' %}active{% endif %}" data-bs-toggle="dropdown" href="#">Volunteers</a>
Similar issue to before, though less likely to be surprising since the second match doesn't contain the first.

2023-09-25 12:50 UTC, jennifer-richards approved these changes

2023-09-25 13:11 UTC, jennifer-richards commented
I think I gave some bad advice - I was looking at creating the template tag I suggested as an alternative to the explosion of "or" clauses in the `selected` tests and realized that it can be done like
```
{% if selected in "a,b,c,d,e,f"|split:"," %}
```
using what we've already got. Sorry for pointing you toward exploding the logic - if you'd like I can clean that up here or in a separate PR.

2023-09-25 14:48 UTC, jennifer-richards requested changes

2023-09-25 14:48 UTC, jennifer-richards commented on ietf/templates/nomcom/nomcom_public_base.html
> +                <a class="nav-link dropdown-toggle {% if selected in 'eligibl,volunteers'|split:',' %}active{% endif %}" data-bs-toggle="dropdown" href="#">Volunteers</a>
Typo - `eligible` became `eligibl`

2023-09-25 15:01 UTC, jennifer-richards approved these changes

2023-09-29 15:13 UTC, merged