feat: subseries
ietf-tools/datatracker pull request #6347
Opened 2023-09-21 17:54 UTC by rjsparks

2023-09-21 20:08 UTC, jennifer-richards requested changes
A couple questions and an HTML lint inline. Also the tests look like they need to be updated - at least, I don't think those are random failures.

In the search view and in the individual subseries pages, contained rfcs are listed in arbitrary order - some are increasing rfc numbers, some are decreasing, and I imagine there are probably some mixed. If that's not significant (and I don't think it is based on how the contents are modeled), it'd be nice to sort those.

2023-09-21 20:08 UTC, jennifer-richards commented on ietf/templates/doc/index_subseries.html
> +          <p><a href="{% url 'ietf.doc.views_doc.document_main' name=rfc.name %}"">{{rfc.name}}</a> : {{rfc.title}}</p>
Extra `"` in the `<a...>` opening tag

2023-09-21 20:15 UTC, rjsparks commented on ietf/sync/rfceditor.py
> +                        subseries_doc.docevent_set.create(type=f"{subseries_slug}_history_marker", by=system, desc=f"No history of this {subseries_slug.upper()} document is currently available in the
intended both to be the same - thought mutated during work - will normalize.

2023-09-21 20:18 UTC, rjsparks commented on ietf/sync/rfceditor.py
> +                        subseries_doc.docevent_set.create(type=f"{subseries_slug}_history_marker", by=system, desc=f"No history of this {subseries_slug.upper()} document is currently available in the
>(comment applies both here and below)

I don't see where this applies below?

2023-09-21 20:19 UTC, rjsparks commented on ietf/sync/rfceditor.py
> +                        subseries_doc.docevent_set.create(type=f"{subseries_slug}_history_marker", by=system, desc=f"No history of this {subseries_slug.upper()} document is currently available in the
ah nevermind

2023-09-22 00:45 UTC, jennifer-richards reviewed
Changes you've made look good so far.

2023-09-22 22:55 UTC, jennifer-richards approved these changes

2023-09-22 22:55 UTC, merged