fix: Remove Google from doc search action
ietf-tools/datatracker pull request #6630
Opened 2023-11-10 10:08 UTC by richsalz

Remove google from the "search lists" pulldown on the document page.

2023-11-28 15:50 UTC, rjsparks commented
I think we should address what Rich points to above before (or instead of) merging this.

2023-11-28 15:51 UTC, rjsparks commented
Just to make it clearer what the state of this is, I'm going to leave it open and request changes, but I'm not asking @richsalz for anything right now - wait for some design thinking please.

2023-11-28 15:52 UTC, rjsparks requested changes
Lets hold this for future conversation.

2024-01-05 21:31 UTC, richsalz commented
@rjsparks please re-open; i removed the branch (which closed the PR), and then restored it.  oops.  Want to keep the commentary.  Or I can add the info here as notes to #6590 if that's better.

2024-01-05 21:37 UTC, rjsparks commented
The commentary won't go away if you close the PR - we'll still be able to navigate to it from the issue.

2024-01-08 14:28 UTC, jennifer-richards commented
Gah, adding to the complexity here I just accidentally closed this when I meant to close the window... sorry!

2024-02-01 22:42 UTC, closed without merging

2024-02-01 22:42 UTC, rjsparks commented
Closing this again - see #7009