fix: change verbosity of api key purge mgmt command
ietf-tools/datatracker pull request #6758
Opened 2023-12-11 14:37 UTC by rjsparks

2023-12-11 14:45 UTC, jennifer-richards approved these changes

2023-12-11 14:54 UTC, rjsparks commented
Holding until after the feat/rfc release.

2023-12-14 15:57 UTC, jennifer-richards requested changes
Needs test fixup

2023-12-14 21:03 UTC, jennifer-richards approved these changes

2023-12-14 21:04 UTC, merged