feat: Allow entering agenda text directly
ietf-tools/datatracker pull request #6792
Opened 2023-12-17 23:27 UTC by pselkirk

Fixes #6532

2023-12-17 23:34 UTC, pselkirk commented
For whatever reason (because I don't know javascript), the script that shows the appropriate file/text input box (taken from complete-review.js) doesn't hide the label of the hidden field.

2023-12-18 16:18 UTC, jennifer-richards commented
> For whatever reason (because I don't know javascript), the script that shows the appropriate file/text input box (taken from complete-review.js) doesn't hide the label of the hidden field.

The issue is that the `bootstrap_form` call is rendering the fields like (paraphrasing)
```html
<div class="mb-3">
  <label class="form-label" ...>Agenda text</label>
  <textarea id="id_content" name="content" ...></textarea>
</div>
```
and you are selecting for `[name="content"]`, which selects only the `<textarea/>`.

Easiest thing to do is to change line 54 of the template to `var row = form.find(selector).parent();` so you hide the whole `<div>...</div>` wrapper.  It's somewhat fragile, but I don't see a way to more directly label and select the wrapper `<div/>`.

Also, not sure if you're ready for review, but the JS code should go in its own module like is done for `complete-review.js` so that it can be packaged properly.

2023-12-18 18:24 UTC, pselkirk commented
> `var row = form.find(selector).parent();`

Thanks, that was the nudge I needed.

> the JS code should go in its own module like is done for `complete-review.js` so that it can be packaged properly.

Yeah, I just wanted to get the JS working before going through the packaging step.

2023-12-19 14:01 UTC, jennifer-richards requested changes
Suggestion inline - I'm open to discussion if you think it's preferable to stick with the status code checks as they are

2023-12-19 19:19 UTC, pselkirk commented on ietf/meeting/tests_views.py
> +        self.assertEqual(r.status_code, 302)
Sure, it's an easy enough change, and it's a more complete test.

2023-12-19 23:37 UTC, jennifer-richards approved these changes

2023-12-20 22:40 UTC, merged