feat: Import IESG artifacts into the datatracker
ietf-tools/datatracker pull request #6908
Opened 2024-01-10 19:16 UTC by rjsparks

2024-01-10 21:35 UTC, jennifer-richards requested changes
Only partially reviewed, but I think the tz handling is fragile and should probably be fixed. I expect that the dev machines will show incorrect times on migrated data. (If not, then I must be mistaken in my comments.)

2024-01-10 21:35 UTC, jennifer-richards commented on ietf/meeting/management/commands/import_iesg_minutes.py
> +    def utc_from_la_time(time):
This helper seems fragile to me, but I may not understand what it's trying to do. What I _think_ it's meant to do is to interpret a naive `datetime` as `Los_Angeles` time and convert it to an aware `datetime` in UTC.

If that's correct, it should be `time.replace(tzinfo=Zoneinfo("America/Los_Angeles").astimezone(datetime.timezone.utc)`. As is, it _will_ do the right thing on production, but not on machines with system time zones other than US Pacific time. 

E.g., on my laptop (which uses Atlantic time),
```python
>>> naive = datetime.datetime(2016, 6, 10, 7, 0)
>>> aware = naive.astimezone(ZoneInfo("America/Los_Angeles"))
>>> str(naive)
'2016-06-10 07:00:00'
>>> str(aware)
'2016-06-10 03:00:00-07:00'
>>> str(aware.astimezone(datetime.timezone.utc))
'2016-06-10 10:00:00+00:00'
```
(note the second output - the time it's representing is 3AM in the pacific time zone, not 7AM)

On IETFA, the output is different for the same inputs:
```python
>>> str(naive)
'2016-06-10 07:00:00'
>>> str(aware)
'2016-06-10 07:00:00-07:00'
>>> str(aware.astimezone(datetime.timezone.utc))
'2016-06-10 14:00:00+00:00'
```

Using `replace()` instead, on my machine:
```python
>>> better_aware = naive.replace(tzinfo=ZoneInfo("America/Los_Angeles"))
>>> str(better_aware)
'2016-06-10 07:00:00-07:00'
>>> str(better_aware.astimezone(datetime.timezone.utc))
'2016-06-10 14:00:00+00:00'
```
and on IETFA
```python
>>> better_aware = naive.replace(tzinfo=ZoneInfo("America/Los_Angeles"))
>>> str(better_aware)
'2016-06-10 07:00:00-07:00'
>>> str(aware.astimezone(datetime.timezone.utc))
'2016-06-10 14:00:00+00:00'
```

2024-01-10 21:35 UTC, jennifer-richards commented on ietf/meeting/management/commands/import_iesg_minutes.py
> +        dt = bare_datetime.replace(hour=7).astimezone(ZoneInfo("America/Los_Angeles"))
As I describe in my long comment below, you want to use `replace()` instead of `astimezone()` to set the tzinfo on a naive datetime.

2024-01-18 17:33 UTC, jennifer-richards requested changes
A few comments - I think the tz stuff is still in need of changes.

The n+1 business looks good to me, but I'm still thinking about how it can be made more maintainable.

2024-01-18 21:37 UTC, rjsparks commented on ietf/meeting/management/commands/import_iesg_minutes.py
> -        return time.astimezone(ZoneInfo("America/Los_Angeles")).astimezone(
right - I had this correct earlier but an overzealous replace botched it.

2024-01-19 14:34 UTC, jennifer-richards submitted a review, later dismissed
My concerns are addressed.

I'm a little uneasy about the monkey patched optimizations - it'd be nice to find a better pattern for that. I don't see a reason to hold this up for solving that, though.

2024-01-19 21:32 UTC, rjsparks commented on ietf/group/management/commands/import_iesg_appeals.py
> +                        bits = bits.decode("macintosh")
bits aren't bytes.

2024-02-20 17:23 UTC, jennifer-richards approved these changes

2024-02-20 22:35 UTC, merged