Add celery tasks for idnits2 and bibxml file generation
ietf-tools/datatracker pull request #7204
Opened 2024-03-16 08:07 UTC by russhousley

Add celery tasks for idnits2 and bibxml file generation. Fixes #7192

2024-03-21 00:05 UTC, jennifer-richards requested changes
One typo, one small change I think we should make.

2024-03-21 00:05 UTC, jennifer-richards commented on ietf/doc/tests_tasks.py
> +    def test_generate_bibxml_files_for_recent_drafts_task_with_bad_vakue(self):
typo: `vakue` -> `value`

2024-03-21 00:36 UTC, russhousley commented on ietf/doc/utils.py
> +            raise ee
Sounds fine to me.

2024-03-21 00:36 UTC, russhousley commented on ietf/doc/tests_tasks.py
> +    def test_generate_bibxml_files_for_recent_drafts_task_with_bad_vakue(self):
Goof catch.  I read past it many times.

2024-07-15 17:12 UTC, jennifer-richards commented
In the scramble to cut over to the new infrastructure, I lost track of this PR and wound up reimplementing it slightly differently. I'm merging that over so we can merge this.

2024-07-15 17:13 UTC, jennifer-richards submitted a review, later dismissed

2024-07-16 14:44 UTC, jennifer-richards approved these changes

2024-08-07 14:18 UTC, merged