fix: return to ballotpopup
ietf-tools/datatracker pull request #7858
Opened 2024-08-26 20:47 UTC by holloway

A valid 'return to' param wasn't in the allow list. This updates the allow list and adds a test.

2024-08-26 20:49 UTC, jennifer-richards submitted a review, later dismissed

2024-08-26 22:17 UTC, holloway commented
fyi @jennifer-richards: @rjsparks pointed out that the 'return to' param when coming from a modal doesn't make sense. Bootstrap modals are configured to scrape an modal template route (eg `/doc/draft-ietf-opsawg-ipfix-tcpo-v6eh/ballotpopup/998718/`) and then display that as a modal, so the 'return to' is the modal template route not the originating page from which the modal opened. This means there's a new layer of indirection when opening via modals, so the fix is to

* update the modal template route to take a param, rather than using `request.path`, and validate the param using the same logic as before.
* ensure every place that uses the ballot_icon template tag is added to the allow list of valid 'return to' route handlers. This is a bit like playing whack-a-mole, but I think I've found every usage.

2024-08-27 13:33 UTC, rjsparks commented
> This is a bit like playing whack-a-mole, but I think I've found every usage.

2024-08-27 13:40 UTC, jennifer-richards requested changes
Looking good, butI think a valid return point was missed. There are a couple minor bits of cleanup I suggest.

2024-08-27 21:42 UTC, holloway commented on ietf/doc/tests_ballot.py
> +            lambda: parse_ballot_edit_return_point('/', 'draft-ietf-opsawg-ipfix-tcpo-v6eh', '998718'),
Done

2024-08-27 21:43 UTC, holloway commented on ietf/doc/templatetags/ballot_icon.py
> +            ballot_edit_return_point_param)
Good idea. Done

2024-08-28 02:15 UTC, jennifer-richards approved these changes
Lgtm. I didn't have a chance to double check that all the places `search_result_row.html` is included are in the allowed view list.

2024-08-28 03:06 UTC, holloway commented
@jennifer-richards fyi here's my notes on tracing back from `search_result_row.html`

```
search_result_row.html
	search_results.html
		view_list.html
			ietf/community/views.view_list
		drafts_for_ad.html
			ietf/doc/views_search.docs_for_ad
		drafts_in_last_call.html
			ietf/doc/views_search.drafts_in_last_call
		recent_drafts.html
			ietf/doc/views_search.recent_drafts
		search/search.html
			ietf/doc/views_search.search
		group_documents.html
			ietf/group/views.group_documents
		stream_documents.html
			ietf/group/views.stream_documents
	agenda_documents.html
		ietf/iesg/views.agenda_documents
```

(those views are in the allowed list)

2024-08-28 12:50 UTC, rjsparks approved these changes

2024-08-28 12:51 UTC, merged