feat: remove "AD is watching" state
ietf-tools/datatracker pull request #7960
Opened 2024-09-20 23:29 UTC by jennifer-richards

Fixes #6316

2024-09-20 23:30 UTC, jennifer-richards commented
Created as draft because there are still a bunch of references to the `"watching"` state in code and tests that need to be dealt with.

2024-09-23 14:15 UTC, jennifer-richards commented
In deciding what to do with docs in the "AD is watching" state (of which there were 60 as of a ~week-old dev DB snapshot), I'm running into #5560 - my first pass at the migration put expired drafts into `dead`, but it is not clear whether that's the right thing to do. From the discussion there, it seems that perhaps `idexists` would be better. Relevant, the first few `watching` drafts I looked at were similar to https://datatracker.ietf.org/doc/draft-murata-kohn-lilley-xml/history/, where the history incorrectly indicates they're in the `dead` state.

2024-09-23 14:21 UTC, rjsparks commented
yes, many transitions to dead should now be transitions to idexist. I can't think of any place we should have code choosing the dead state - an AD should have to choose that explicitly.

The code that does is leftover from before we made an idexists state for the draft-iesg state machine

2024-09-24 15:27 UTC, rjsparks commented on ietf/doc/migrations/0024_remove_ad_is_watching_states.py
> +            desc=f"{draft_iesg_state_type.label} changed to <b>{idexists_state.name}</b> from {watching_state.name}",
cringing at the html tags, but keeping the set of things to mutate later regular was a good call

2024-09-24 15:37 UTC, rjsparks requested changes
Once guidance to new ads change requested.

2024-09-24 15:37 UTC, rjsparks commented on ietf/templates/doc/draft/change_state.html
> +            This document is in IESG state "Dead". It is unusual to change this to
Add back the "never be used as a replacement for Begin IESG Processing". (New IESG members assume that moving things into pubreq will have all the side-effects that the form/view for Begin IESG Processing applies, but that's not possible.

We could also consider not allowing the document to make any other transition in this particular case.

2024-09-24 15:46 UTC, rjsparks approved these changes, later dismissed

2024-09-24 17:12 UTC, rjsparks approved these changes

2024-09-24 17:13 UTC, merged