fix: fix wg anchor tags in areas page
ietf-tools/datatracker pull request #7995
Opened 2024-10-01 21:05 UTC by microamp

fixes #7994 

In https://github.com/ietf-tools/datatracker/blob/main/ietf/templates/group/active_wgs.html, it uses `upper`,
```jinja
    {% for area in areas %}
        <h2 class="mt-5" id="{{ area.acronym|upper }}">{{ area.name }} ({{ area.acronym|upper }})</h2>
```

so it's now doing the same on the area's side.

2024-10-01 21:45 UTC, microamp commented
The IESG agenda page also has this issue. It's been addressed here, https://github.com/ietf-tools/datatracker/pull/7995/commits/4b2e45ab296d66a50d8c2c44cb21522aa6952c73.

2024-10-02 15:13 UTC, jennifer-richards submitted a review, later dismissed
lgtm

Only comment is that there's a slight tension in hard-coding the `/wg/` URL in the tests vs using `urlreverse()` to find it. I think it's probably ok either way because we're not likely to move the URL and it's a quick / obvious fix if we do.

2024-10-02 16:51 UTC, rjsparks requested changes
Please address Jennifer's concern - use urlreverse instead of assuming /wg/).
I'd also suggest using jQuery to look for the element in the right place in the document rather than using assertContains - that may let you ignore the path part altogether and let you just test that the terminal part is capitialized.

2024-10-02 19:17 UTC, jennifer-richards commented
> jQuery

pyquery?

2024-10-02 19:21 UTC, rjsparks commented
yes, I meant pyquery

2024-10-02 22:24 UTC, rjsparks approved these changes

2024-10-02 22:37 UTC, jennifer-richards approved these changes

2024-10-02 22:37 UTC, merged