refactor: update secretariat dashboard style
ietf-tools/datatracker pull request #8140
Opened 2024-11-03 15:38 UTC by rpcross

2024-11-03 16:26 UTC, rjsparks approved these changes, later dismissed

2024-11-15 18:40 UTC, rjsparks commented
Please see the failing tests - I think there's a problem around `/static/ietf/js/announcement.js`

2024-11-15 18:41 UTC, rjsparks requested changes
Please see the failing tests - I think there's a problem around `/static/ietf/js/announcement.js`

2025-03-21 08:53 UTC, rjsparks commented
Hi @rpcross this seems to have fallen through the cracks?

2025-03-21 20:57 UTC, Michealinc reviewed
Explict

2025-03-21 21:03 UTC, Michealinc reviewed
Explict

2025-03-25 16:24 UTC, jennifer-richards commented
Probably should apply Black styling to the Python while you're at it?

2025-04-23 16:24 UTC, jennifer-richards approved these changes

2025-04-23 16:26 UTC, rjsparks approved these changes

2025-04-23 16:26 UTC, merged