feat: Use idnits3 for post submission nits check
ietf-tools/datatracker pull request #8169
Opened 2024-11-06 17:47 UTC by kesara

Fixes #8107

2024-11-07 13:25 UTC, jennifer-richards approved these changes

2024-11-07 13:25 UTC, jennifer-richards commented on ietf/doc/tests.py
> +        draft = WgDraftFactory(name="draft-ietf-moon-test",rev="01", create_revisions=range(0,2))
A comment as to why you're setting up this particular arrangement of revisions would be helpful

2024-11-07 13:27 UTC, jennifer-richards requested changes
Oops, meant to request changes for the comment (code itself looks fine)

2024-11-07 16:10 UTC, rjsparks commented
If someone really wanted the v2 nits, can they get back to them quickly?

2024-11-14 23:26 UTC, rjsparks commented
Nudge:

2024-11-14 23:59 UTC, kesara commented
> If someone really wanted the v2 nits, can they get back to them quickly?

No there are no quick links for that. Author tools just shows the output from idnits.

2024-11-15 18:16 UTC, rjsparks commented
so maybe instead of replacing the idnits2 button, we provide both idnits2 and idnits3 buttons until idnits3 becomes the thing in the submit path?

2024-11-16 07:57 UTC, cabo commented
Where can I find idnits3?
https://github.com/ietf-tools/idnits does not appear to be in a useful state.

2024-11-16 08:29 UTC, kesara commented
> Where can I find idnits3? https://github.com/ietf-tools/idnits does not appear to be in a useful state.

@cabo, You can install with `npm` [^1] or use [idnits3 on Auhtor Tools](https://author-tools.ietf.org/idnits3).

[^1]: https://github.com/ietf-tools/idnits?tab=readme-ov-file#installation

2024-11-16 08:33 UTC, kesara commented
> so maybe instead of replacing the idnits2 button, we provide both idnits2 and idnits3 buttons until idnits3 becomes the thing in the submit path?

One of the motivations of this change is to stop unnecessary idnits2 checks because this makes a call to datatracker which seems slow and could affect datatracker performance.

2024-11-16 09:52 UTC, cabo commented
> @cabo, You can install with `npm` [1](#user-content-fn-1-0f99bd6715f56c1bbcc1a7817eaea9a9) or use [idnits3 on Auhtor Tools](https://author-tools.ietf.org/idnits3).

OK, I have that, so "3.0.0-alpha.36" appears to be the most recent revision.
That is not very useful.

https://author-tools.ietf.org/api/idnits3?url=https://www.ietf.org/archive/id/draft-ietf-cbor-cddl-more-control-07.xml
https://mailarchive.ietf.org/arch/msg/last-call/IM2SIo26RzBq0tO0lG5JETyGGNo

2024-11-17 20:21 UTC, kesara commented
> > @cabo, You can install with `npm` [1](#user-content-fn-1-0f99bd6715f56c1bbcc1a7817eaea9a9) or use [idnits3 on Auhtor Tools](https://author-tools.ietf.org/idnits3).
> 
> OK, I have that, so "3.0.0-alpha.36" appears to be the most recent revision. That is not very useful.
> 
> https://author-tools.ietf.org/api/idnits3?url=https://www.ietf.org/archive/id/draft-ietf-cbor-cddl-more-control-07.xml https://mailarchive.ietf.org/arch/msg/last-call/IM2SIo26RzBq0tO0lG5JETyGGNo

@cabo, idnits v3 is still in alpha stage of development. But you can report any issues to idnits repository[^1] so we can correct them early.

[^1]: https://github.com/ietf-tools/idnits/issues/new

2024-11-19 15:55 UTC, rjsparks commented
We need to signal that this is a new, not yet complete, and under development tool. Maybe we can use a tooltip, but there are accessibility concerns with that. Maybe we should put it on its own row with explanatory text? Other ideas?

2025-03-10 21:23 UTC, rjsparks commented
Maybe we can land this one during the 122 codesprint?

2025-03-15 04:31 UTC, kesara commented
@rjsparks How about 
<img width="278" alt="Screenshot 2025-03-15 at 11 31 20" src="https://github.com/user-attachments/assets/34f272ea-a6b7-48da-8435-d65436ac302f" />

2025-03-21 20:56 UTC, Michealinc reviewed
Explict

2025-07-19 09:03 UTC, evyncke commented
Humm indeed #9167 is similar (I will then close it if I have the right to do so).

Else, any reason why the PR is not merged ? (unclear from the above comments)

2025-11-01 19:23 UTC, kesara commented
@rjsparks, With #9175 DT already displays id-nits3 for the IESG on the doc page.
Is there any value in working on this?

2025-11-03 22:03 UTC, rjsparks commented
The original proposal of this PR was to make the link available to everybody - we're probably there, but should label the idnits3 button beta until it is out of beta.

2025-11-06 19:25 UTC, kesara commented
Closing this as solution for #8107 is removing role checks in #9175.

2025-11-06 19:25 UTC, closed without merging