fix: test file existance using metadata
ietf-tools/datatracker pull request #8292
Opened 2024-12-02 15:08 UTC by rjsparks

Without something like this, each view of a draft's main page reads the entire file twice.

2024-12-02 15:24 UTC, jennifer-richards requested changes
This is really begging to be refactored the rest of the way using `pathlib.Path`. I won't insist, though.

However, `text_exists()` is not used - I assume you have a use case in mind? Seems like the call should come in with the function.

2024-12-02 15:47 UTC, rjsparks commented
More significant refactoring coming in with the blob work, but in the meantime:...

2024-12-02 15:57 UTC, jennifer-richards approved these changes, later dismissed
The change from catching IOError to testing path.exists() introduces a (tiny) window for a race. It may also mean additional exotic read failures turn into server errors. I think that is ok, but calling it out in case you think it might come up when the server is operating normally.

2024-12-05 01:16 UTC, jennifer-richards approved these changes

2024-12-05 14:46 UTC, merged